function(add_unit_test_dir DIR_PATH)
    if(NOT EXISTS ${DIR_PATH})
        message(FATAL_ERROR "Directory ${DIR_PATH} does not exist")
    endif()

    file(GLOB_RECURSE TEST_FILES ${DIR_PATH}/*.cxx)
    if(TEST_FILES STREQUAL "")
        message(FATAL_ERROR "No test files found in ${DIR_PATH}")
    endif()

    enable_testing()
    foreach(TEST_FILE ${TEST_FILES})
        get_filename_component(TEST_NAME ${TEST_FILE} NAME_WE)
        add_executable(NCXT_Fenix_TEST_${TEST_NAME} ${TEST_FILE})
        target_link_libraries(NCXT_Fenix_TEST_${TEST_NAME} ${PROJECT_NAME}_LIB)
        add_test(NCXT_Fenix_TEST_${TEST_NAME} NCXT_Fenix_TEST_${TEST_NAME})
    endforeach()
endfunction()
